# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2021-08-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(help_text='Provide the bind user password here!', max_length=50, null=True)),
                ('email_id', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=13, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
