# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2021-08-24 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.CharField(max_length=50)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Timeline',
            },
        ),
    ]
