# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2021-08-24 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeline',
            new_name='TwitterTimeline',
        ),
        migrations.AlterModelTable(
            name='twittertimeline',
            table='TwitterTimeline',
        ),
    ]
